{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-pinocchio
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2-feature-classifier {{ qiime2_epoch }}.*
    - samtools
    - minimap2
    - beautifulsoup4
    - nanoplot
    - chopper
    - gzip

test:
  requires:
    - coverage
    - pytest-cov
  imports:
    - q2_pinocchio
    - qiime2.plugins.pinocchio
  commands:
    - pytest --cov q2_pinocchio --cov-report xml:coverage.xml --pyargs q2_pinocchio

about:
  home: https://github.com/bokulich-lab/q2-pinocchio
  license: BSD-3-Clause
  license_family: BSD
